### ISSUE TITLE
Is this tool still recommended?

### ISSUE THREAD

**Issue by openjck** [znevrly/cucumber-junit-convert#19]
Hi @znevrly. Thanks for this helpful project.

I see that Cucumber [appears to output JUnit natively](https://cucumber.io/docs/cucumber/reporting/?lang=javascript#built-in-reporter-plugins). That may be a new addition. I haven't used that _or_ this project, but do they serve different needs? Is this tool needed given that Cucumber now outputs JUnit natively?

**Comment by znevrly** [comment]
No, actually since CucumberJS 9+ (just guess) is not needed anymore

**Comment by openjck** [comment]
Thank you, and thank you for making JUnit export available even before Cucumber did. 🙂
